### ISSUE TITLE
DeepNorm question

### ISSUE THREAD

**Issue by ezeli** [labmlai/annotated_deep_learning_paper_implementations#145]
https://github.com/labmlai/annotated_deep_learning_paper_implementations/blob/25ad4d675039f1eccabb2f7ca6c14b11ee8d02c1/labml_nn/normalization/deep_norm/__init__.py#L105
The self.layer_norm is not used in the forward function. And the self.alpha should be multiplied by x, not gx.

The correct forward function might be:
```python
def forward(self, x: torch.Tensor, gx: torch.Tensor):
    return self.layer_norm(self.alpha * x + gx)
```

**Comment by vpj** [comment]
Thanks 🙏 

Fixed it https://github.com/labmlai/annotated_deep_learning_paper_implementations/commit/0eb74d7b200a3258c7e61aa59ee231d86c9a4671

**Comment by everks** [comment]
thanks for your great work, but I think you are not fixed this? the alpha should be multiplied by x, not gx?
